version: '3.1'

services:
  postgres:
    image: postgres:15.1-alpine
    container_name: db_ease
    environment:
      POSTGRES_DB: ease
      POSTGRES_USER: ease
      POSTGRES_PASSWORD: ease
    volumes:
      - ease_vol:/var/lib/postgresql/data
    ports:
      - '5400:5432'

  redis:
    image: redis:latest
    container_name: cache_ease
    ports:
      - '6000:6379'
    volumes:
      - ease_cache_vol:/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: explore_ease_server
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - postgres
      - redis

volumes:
  ease_vol:
  ease_cache_vol:
  ease_main:
